version: '3.8'

services:
  # --- Config Servers (cfgrs) ---
  configs1:
    container_name: configs1
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "10001:27017"
    volumes:
      - configs1:/data/db

  configs2:
    container_name: configs2
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "10002:27017"
    volumes:
      - configs2:/data/db

  configs3:
    container_name: configs3
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "10003:27017"
    volumes:
      - configs3:/data/db

  # --- Shard 1 Replica Set (shard1rs) with 2 members ---
  shard1s1:
    container_name: shard1s1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "20001:27017"
    volumes:
      - shard1s1:/data/db

  shard1s2:
    container_name: shard1s2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "20002:27017"
    volumes:
      - shard1s2:/data/db

  # --- Shard 2 Replica Set (shard2rs) with 2 members ---
  shard2s1:
    container_name: shard2s1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "21001:27017"
    volumes:
      - shard2s1:/data/db

  shard2s2:
    container_name: shard2s2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "21002:27017"
    volumes:
      - shard2s2:/data/db

  # --- Shard 3 Replica Set (shard3rs) with 2 members ---
  shard3s1:
    container_name: shard3s1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "22001:27017"
    volumes:
      - shard3s1:/data/db

  shard3s2:
    container_name: shard3s2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - "22002:27017"
    volumes:
      - shard3s2:/data/db

  # --- Mongos Router ---
  mongos:
    container_name: mongos
    image: mongo:latest
    depends_on:
      - configs1
      - configs2
      - configs3
      - shard1s1
      - shard1s2
      - shard2s1
      - shard2s2
      - shard3s1
      - shard3s2
    command: >
      mongos --configdb cfgrs/configs1:27017,configs2:27017,configs3:27017
      --bind_ip_all --port 27017
    ports:
      - "30000:27017"

volumes:
  configs1: {}
  configs2: {}
  configs3: {}
  shard1s1: {}
  shard1s2: {}
  shard2s1: {}
  shard2s2: {}
  shard3s1: {}
  shard3s2: {}

